### PR TITLE
Updated nl-dutch.properties

### PR DESCRIPTION
**Pull request by milo526**
Included new translations for the nl-dutch localization.

### CODE REVIEW

**Comment by Kezz101** [comment]
I speak absolutely no dutch but is this all up to date still? I'm more than happy to merge this if so!

**Comment by milo526** [comment]
Well it wasn't before I updated but now it is!

**Comment by jacklin213** [comment]
Hold up with the merge, Need to commit some stuff from my computer first so that no conflicts happen :)

**Comment by jacklin213** [comment]
Thanks, sorry took forever to get around to it

**Pull request merged**
